#!/usr/bin/env python
# -*- coding: utf-8 -*-

#epsilon = 1e-12
#mask_outside=1e17
# usermodules = [{'name':'module1', 'abspath':'/path/to/module1.py'},
#                {'name':'module2', 'abspath':'/path/to/module2.py'}
#                ]
#use_footprints_as_builder = True
#usercolormaps = {'my_cmap':'/path/to/my_cmap.cmap'}
#implemented_formats = ['FA',]
noninteractive_backend = "Agg"
usercolormaps={'biais': '/home/ormieresl/.epygram/palettes/biais.json',
        'biais_v1': '/home/ormieresl/.epygram/palettes/biais_v1.json',
        'biais_v4': '/home/ormieresl/.epygram/palettes/biais_v4.json',
        'biais_v4_grey': '/home/ormieresl/.epygram/palettes/biais_v4_grey.json'}
